name: ColoredBooked
description: Add format codes to your books!
author: Raus
main: com.raus.coloredBooks.Main
version: 1.0
api-version: 1.15

commands:
  coloredbooks:
    description: Colored Books
    default: true
    usage: "Usage: /coloredbooks [info|preview|copy]"
    aliases: [cbooks, cb]

permissions:
  coloredbooks.preview:
    default: true
    description: Allows you to make a formatted preview of a book
  coloredbooks.copy:
    default: true
    description: Allows you to make formatted copies of a book